CREATE TABLE measurement (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  time datetime NOT NULL,
  location varchar(50) NOT NULL,
  pm10 decimal(10,3) NOT NULL,
  pm2_5 decimal(10,3) NOT NULL,
  gas decimal(10,3) NOT NULL,
  UNIQUE (time, location)
);

